### ISSUE TITLE
Sagemaker SSD object detection endpoint error (can't set content_type)

### ISSUE THREAD

**Issue by peymvn** [aws/amazon-sagemaker-examples#1885]
Some months ago, before Sagemaker v2, I created several object detection models using amazon's default SSD model image. I tested and deployed those models successfully, exactly like the documentation.
Now, I wanted to use those models as endpoints again. I deployed the model and created an endpoint using:
```python
from sagemaker.predictor import Predictor
def predict_wrapper(endpoint, session):
    return Predictor(endpoint, session)

od_model = sagemaker.model.Model(image_uri=od_image, model_data=s3_model_location, role=role, predictor_cls=predict_wrapper)
object_detector = od_model.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge', accelerator_type ='ml.eia1.medium')
```
But when I go to make an inference like what we see in the sample notebooks, it raises an AttributeError, when it reaches the block that we should determine the content type as 'image/jpeg':

```python
file_name = 'test.jpg'

with open(file_name, 'rb') as image:
    f = image.read()
    b = bytearray(f)
    ne = open('n.txt','wb')
    ne.write(b)
    
object_detector.content_type = 'image/jpeg'
results = object_detector.predict(b)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-2db06c1ce88d> in <module>
      1 # object_detector.enable_data_capture()
----> 2 object_detector.content_type = 'image/jpeg'

AttributeError: can't set attribute
```

I checked out the changes in the Sagemaker while updating to version 2 but could not find any helpful resources related to the MIME type of input data.

**Comment by aaronmarkham** [comment]
I know Paul recently fixed some notebooks around this same problem.

**Comment by peymvn** [comment]
Hi @paul-cb, could you please help me with this issue? I took a look at your commits but could not find anything related to the content type error.

**Comment by paul-cb** [comment]
Hi @peymvn, I fixed something similar to this. Anyways I'm on it now, will update you on this shortly.

**Comment by paul-cb** [comment]
So in v2 you don't directly set `content_type` instead you set the content type in a Serializer instance. You can either do this in the Predictor's constructor or by setting `predictor.serializer` afterwards. Note that you can use an already created serializer class that allows you to specify a `content_type` or alternatively implement a class where you customize it to handle `content_type`.

**Comment by thasin96** [comment]
@peymvn - I am able to fix the issue by providing `initial_args` parameter in predict function. 

```
Ex: object_detector.predict(b, initial_args={'ContentType': 'image/jpeg'})
```

**Comment by paul-cb** [comment]
This is solved.

**Comment by bonzoq** [comment]
`object_detector.predict(b, initial_args={'ContentType': 'image/jpeg'})`

still doesn't work. I get:

ValidationError: An error occurred (ValidationError) when calling the InvokeEndpoint operation: 1 validation error detected: Value at 'body' failed to satisfy constraint: Member must not be null

Any ideas?

**Comment by nizamk** [comment]
Faced the same issue as @peymvn.

Resolved as per suggestion by @thasin96
